### PR TITLE
Placeholder png added

### PR DESCRIPTION
**Pull request by Yugal41735**
# Description

If the user does not insert the image a placeholder png has been added, so that broken image does not show if image is not added.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @Yugal41735, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by Yugal41735** [comment]
Could u check whether is it working or not
image

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @Yugal41735! You're now able to merge the PR.

**Pull request merged**
